deployment:
  replicaCount: 2
container:
  name : "svc-app"
  port: 8000
image:
  name: "abdelrahman1111/start-with-docker:python-final"
service:
  name: "service-app"
  type: "NodePort"
  nodePort: 30007
  targetPort: 8000
pod:
  label : "my-pod"
